// Code generated by entc, DO NOT EDIT.

package accounts

import (
	"time"
)

const (
	// Label holds the string label denoting the accounts type in the database.
	Label = "accounts"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeFromAccountID holds the string denoting the from_account_id edge name in mutations.
	EdgeFromAccountID = "from_account_id"
	// EdgeToAccountID holds the string denoting the to_account_id edge name in mutations.
	EdgeToAccountID = "to_account_id"
	// Table holds the table name of the accounts in the database.
	Table = "accounts"
	// FromAccountIDTable is the table that holds the from_account_id relation/edge.
	FromAccountIDTable = "transfers"
	// FromAccountIDInverseTable is the table name for the Transfers entity.
	// It exists in this package in order to avoid circular dependency with the "transfers" package.
	FromAccountIDInverseTable = "transfers"
	// FromAccountIDColumn is the table column denoting the from_account_id relation/edge.
	FromAccountIDColumn = "accounts_from_account_id"
	// ToAccountIDTable is the table that holds the to_account_id relation/edge.
	ToAccountIDTable = "transfers"
	// ToAccountIDInverseTable is the table name for the Transfers entity.
	// It exists in this package in order to avoid circular dependency with the "transfers" package.
	ToAccountIDInverseTable = "transfers"
	// ToAccountIDColumn is the table column denoting the to_account_id relation/edge.
	ToAccountIDColumn = "accounts_to_account_id"
)

// Columns holds all SQL columns for accounts fields.
var Columns = []string{
	FieldID,
	FieldOwner,
	FieldBalance,
	FieldCurrency,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	OwnerValidator func(string) error
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance int64
	// BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	BalanceValidator func(int64) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
