// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gomicro/ent/accounts"
	"gomicro/ent/transfers"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountsCreate is the builder for creating a Accounts entity.
type AccountsCreate struct {
	config
	mutation *AccountsMutation
	hooks    []Hook
}

// SetOwner sets the "owner" field.
func (ac *AccountsCreate) SetOwner(s string) *AccountsCreate {
	ac.mutation.SetOwner(s)
	return ac
}

// SetBalance sets the "balance" field.
func (ac *AccountsCreate) SetBalance(i int64) *AccountsCreate {
	ac.mutation.SetBalance(i)
	return ac
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (ac *AccountsCreate) SetNillableBalance(i *int64) *AccountsCreate {
	if i != nil {
		ac.SetBalance(*i)
	}
	return ac
}

// SetCurrency sets the "currency" field.
func (ac *AccountsCreate) SetCurrency(s string) *AccountsCreate {
	ac.mutation.SetCurrency(s)
	return ac
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (ac *AccountsCreate) SetNillableCurrency(s *string) *AccountsCreate {
	if s != nil {
		ac.SetCurrency(*s)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AccountsCreate) SetCreatedAt(t time.Time) *AccountsCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AccountsCreate) SetNillableCreatedAt(t *time.Time) *AccountsCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// AddFromAccountIDIDs adds the "from_account_id" edge to the Transfers entity by IDs.
func (ac *AccountsCreate) AddFromAccountIDIDs(ids ...int) *AccountsCreate {
	ac.mutation.AddFromAccountIDIDs(ids...)
	return ac
}

// AddFromAccountID adds the "from_account_id" edges to the Transfers entity.
func (ac *AccountsCreate) AddFromAccountID(t ...*Transfers) *AccountsCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddFromAccountIDIDs(ids...)
}

// AddToAccountIDIDs adds the "to_account_id" edge to the Transfers entity by IDs.
func (ac *AccountsCreate) AddToAccountIDIDs(ids ...int) *AccountsCreate {
	ac.mutation.AddToAccountIDIDs(ids...)
	return ac
}

// AddToAccountID adds the "to_account_id" edges to the Transfers entity.
func (ac *AccountsCreate) AddToAccountID(t ...*Transfers) *AccountsCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddToAccountIDIDs(ids...)
}

// Mutation returns the AccountsMutation object of the builder.
func (ac *AccountsCreate) Mutation() *AccountsMutation {
	return ac.mutation
}

// Save creates the Accounts in the database.
func (ac *AccountsCreate) Save(ctx context.Context) (*Accounts, error) {
	var (
		err  error
		node *Accounts
	)
	ac.defaults()
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AccountsCreate) SaveX(ctx context.Context) *Accounts {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AccountsCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AccountsCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AccountsCreate) defaults() {
	if _, ok := ac.mutation.Balance(); !ok {
		v := accounts.DefaultBalance
		ac.mutation.SetBalance(v)
	}
	if _, ok := ac.mutation.Currency(); !ok {
		v := accounts.DefaultCurrency
		ac.mutation.SetCurrency(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := accounts.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AccountsCreate) check() error {
	if _, ok := ac.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "owner"`)}
	}
	if v, ok := ac.mutation.Owner(); ok {
		if err := accounts.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "owner": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "balance"`)}
	}
	if v, ok := ac.mutation.Balance(); ok {
		if err := accounts.BalanceValidator(v); err != nil {
			return &ValidationError{Name: "balance", err: fmt.Errorf(`ent: validator failed for field "balance": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "currency"`)}
	}
	if v, ok := ac.mutation.Currency(); ok {
		if err := accounts.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "currency": %w`, err)}
		}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	return nil
}

func (ac *AccountsCreate) sqlSave(ctx context.Context) (*Accounts, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ac *AccountsCreate) createSpec() (*Accounts, *sqlgraph.CreateSpec) {
	var (
		_node = &Accounts{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: accounts.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accounts.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.Owner(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accounts.FieldOwner,
		})
		_node.Owner = value
	}
	if value, ok := ac.mutation.Balance(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: accounts.FieldBalance,
		})
		_node.Balance = value
	}
	if value, ok := ac.mutation.Currency(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accounts.FieldCurrency,
		})
		_node.Currency = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: accounts.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := ac.mutation.FromAccountIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accounts.FromAccountIDTable,
			Columns: []string{accounts.FromAccountIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: transfers.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.ToAccountIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accounts.ToAccountIDTable,
			Columns: []string{accounts.ToAccountIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: transfers.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountsCreateBulk is the builder for creating many Accounts entities in bulk.
type AccountsCreateBulk struct {
	config
	builders []*AccountsCreate
}

// Save creates the Accounts entities in the database.
func (acb *AccountsCreateBulk) Save(ctx context.Context) ([]*Accounts, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Accounts, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AccountsCreateBulk) SaveX(ctx context.Context) []*Accounts {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AccountsCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AccountsCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
