// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gomicro/ent/accounts"
	"gomicro/ent/predicate"
	"gomicro/ent/transfers"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAccounts  = "Accounts"
	TypeTransfers = "Transfers"
)

// AccountsMutation represents an operation that mutates the Accounts nodes in the graph.
type AccountsMutation struct {
	config
	op                     Op
	typ                    string
	id                     *int
	owner                  *string
	balance                *int64
	addbalance             *int64
	currency               *string
	created_at             *time.Time
	clearedFields          map[string]struct{}
	from_account_id        map[int]struct{}
	removedfrom_account_id map[int]struct{}
	clearedfrom_account_id bool
	to_account_id          map[int]struct{}
	removedto_account_id   map[int]struct{}
	clearedto_account_id   bool
	done                   bool
	oldValue               func(context.Context) (*Accounts, error)
	predicates             []predicate.Accounts
}

var _ ent.Mutation = (*AccountsMutation)(nil)

// accountsOption allows management of the mutation configuration using functional options.
type accountsOption func(*AccountsMutation)

// newAccountsMutation creates new mutation for the Accounts entity.
func newAccountsMutation(c config, op Op, opts ...accountsOption) *AccountsMutation {
	m := &AccountsMutation{
		config:        c,
		op:            op,
		typ:           TypeAccounts,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAccountsID sets the ID field of the mutation.
func withAccountsID(id int) accountsOption {
	return func(m *AccountsMutation) {
		var (
			err   error
			once  sync.Once
			value *Accounts
		)
		m.oldValue = func(ctx context.Context) (*Accounts, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Accounts.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAccounts sets the old Accounts of the mutation.
func withAccounts(node *Accounts) accountsOption {
	return func(m *AccountsMutation) {
		m.oldValue = func(context.Context) (*Accounts, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AccountsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AccountsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AccountsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetOwner sets the "owner" field.
func (m *AccountsMutation) SetOwner(s string) {
	m.owner = &s
}

// Owner returns the value of the "owner" field in the mutation.
func (m *AccountsMutation) Owner() (r string, exists bool) {
	v := m.owner
	if v == nil {
		return
	}
	return *v, true
}

// OldOwner returns the old "owner" field's value of the Accounts entity.
// If the Accounts object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountsMutation) OldOwner(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldOwner is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldOwner requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwner: %w", err)
	}
	return oldValue.Owner, nil
}

// ResetOwner resets all changes to the "owner" field.
func (m *AccountsMutation) ResetOwner() {
	m.owner = nil
}

// SetBalance sets the "balance" field.
func (m *AccountsMutation) SetBalance(i int64) {
	m.balance = &i
	m.addbalance = nil
}

// Balance returns the value of the "balance" field in the mutation.
func (m *AccountsMutation) Balance() (r int64, exists bool) {
	v := m.balance
	if v == nil {
		return
	}
	return *v, true
}

// OldBalance returns the old "balance" field's value of the Accounts entity.
// If the Accounts object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountsMutation) OldBalance(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldBalance is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldBalance requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBalance: %w", err)
	}
	return oldValue.Balance, nil
}

// AddBalance adds i to the "balance" field.
func (m *AccountsMutation) AddBalance(i int64) {
	if m.addbalance != nil {
		*m.addbalance += i
	} else {
		m.addbalance = &i
	}
}

// AddedBalance returns the value that was added to the "balance" field in this mutation.
func (m *AccountsMutation) AddedBalance() (r int64, exists bool) {
	v := m.addbalance
	if v == nil {
		return
	}
	return *v, true
}

// ResetBalance resets all changes to the "balance" field.
func (m *AccountsMutation) ResetBalance() {
	m.balance = nil
	m.addbalance = nil
}

// SetCurrency sets the "currency" field.
func (m *AccountsMutation) SetCurrency(s string) {
	m.currency = &s
}

// Currency returns the value of the "currency" field in the mutation.
func (m *AccountsMutation) Currency() (r string, exists bool) {
	v := m.currency
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrency returns the old "currency" field's value of the Accounts entity.
// If the Accounts object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountsMutation) OldCurrency(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCurrency is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCurrency requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrency: %w", err)
	}
	return oldValue.Currency, nil
}

// ResetCurrency resets all changes to the "currency" field.
func (m *AccountsMutation) ResetCurrency() {
	m.currency = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AccountsMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AccountsMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Accounts entity.
// If the Accounts object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountsMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AccountsMutation) ResetCreatedAt() {
	m.created_at = nil
}

// AddFromAccountIDIDs adds the "from_account_id" edge to the Transfers entity by ids.
func (m *AccountsMutation) AddFromAccountIDIDs(ids ...int) {
	if m.from_account_id == nil {
		m.from_account_id = make(map[int]struct{})
	}
	for i := range ids {
		m.from_account_id[ids[i]] = struct{}{}
	}
}

// ClearFromAccountID clears the "from_account_id" edge to the Transfers entity.
func (m *AccountsMutation) ClearFromAccountID() {
	m.clearedfrom_account_id = true
}

// FromAccountIDCleared reports if the "from_account_id" edge to the Transfers entity was cleared.
func (m *AccountsMutation) FromAccountIDCleared() bool {
	return m.clearedfrom_account_id
}

// RemoveFromAccountIDIDs removes the "from_account_id" edge to the Transfers entity by IDs.
func (m *AccountsMutation) RemoveFromAccountIDIDs(ids ...int) {
	if m.removedfrom_account_id == nil {
		m.removedfrom_account_id = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.from_account_id, ids[i])
		m.removedfrom_account_id[ids[i]] = struct{}{}
	}
}

// RemovedFromAccountID returns the removed IDs of the "from_account_id" edge to the Transfers entity.
func (m *AccountsMutation) RemovedFromAccountIDIDs() (ids []int) {
	for id := range m.removedfrom_account_id {
		ids = append(ids, id)
	}
	return
}

// FromAccountIDIDs returns the "from_account_id" edge IDs in the mutation.
func (m *AccountsMutation) FromAccountIDIDs() (ids []int) {
	for id := range m.from_account_id {
		ids = append(ids, id)
	}
	return
}

// ResetFromAccountID resets all changes to the "from_account_id" edge.
func (m *AccountsMutation) ResetFromAccountID() {
	m.from_account_id = nil
	m.clearedfrom_account_id = false
	m.removedfrom_account_id = nil
}

// AddToAccountIDIDs adds the "to_account_id" edge to the Transfers entity by ids.
func (m *AccountsMutation) AddToAccountIDIDs(ids ...int) {
	if m.to_account_id == nil {
		m.to_account_id = make(map[int]struct{})
	}
	for i := range ids {
		m.to_account_id[ids[i]] = struct{}{}
	}
}

// ClearToAccountID clears the "to_account_id" edge to the Transfers entity.
func (m *AccountsMutation) ClearToAccountID() {
	m.clearedto_account_id = true
}

// ToAccountIDCleared reports if the "to_account_id" edge to the Transfers entity was cleared.
func (m *AccountsMutation) ToAccountIDCleared() bool {
	return m.clearedto_account_id
}

// RemoveToAccountIDIDs removes the "to_account_id" edge to the Transfers entity by IDs.
func (m *AccountsMutation) RemoveToAccountIDIDs(ids ...int) {
	if m.removedto_account_id == nil {
		m.removedto_account_id = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.to_account_id, ids[i])
		m.removedto_account_id[ids[i]] = struct{}{}
	}
}

// RemovedToAccountID returns the removed IDs of the "to_account_id" edge to the Transfers entity.
func (m *AccountsMutation) RemovedToAccountIDIDs() (ids []int) {
	for id := range m.removedto_account_id {
		ids = append(ids, id)
	}
	return
}

// ToAccountIDIDs returns the "to_account_id" edge IDs in the mutation.
func (m *AccountsMutation) ToAccountIDIDs() (ids []int) {
	for id := range m.to_account_id {
		ids = append(ids, id)
	}
	return
}

// ResetToAccountID resets all changes to the "to_account_id" edge.
func (m *AccountsMutation) ResetToAccountID() {
	m.to_account_id = nil
	m.clearedto_account_id = false
	m.removedto_account_id = nil
}

// Where appends a list predicates to the AccountsMutation builder.
func (m *AccountsMutation) Where(ps ...predicate.Accounts) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *AccountsMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Accounts).
func (m *AccountsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AccountsMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.owner != nil {
		fields = append(fields, accounts.FieldOwner)
	}
	if m.balance != nil {
		fields = append(fields, accounts.FieldBalance)
	}
	if m.currency != nil {
		fields = append(fields, accounts.FieldCurrency)
	}
	if m.created_at != nil {
		fields = append(fields, accounts.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AccountsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case accounts.FieldOwner:
		return m.Owner()
	case accounts.FieldBalance:
		return m.Balance()
	case accounts.FieldCurrency:
		return m.Currency()
	case accounts.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AccountsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case accounts.FieldOwner:
		return m.OldOwner(ctx)
	case accounts.FieldBalance:
		return m.OldBalance(ctx)
	case accounts.FieldCurrency:
		return m.OldCurrency(ctx)
	case accounts.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Accounts field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case accounts.FieldOwner:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwner(v)
		return nil
	case accounts.FieldBalance:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBalance(v)
		return nil
	case accounts.FieldCurrency:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrency(v)
		return nil
	case accounts.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Accounts field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AccountsMutation) AddedFields() []string {
	var fields []string
	if m.addbalance != nil {
		fields = append(fields, accounts.FieldBalance)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AccountsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case accounts.FieldBalance:
		return m.AddedBalance()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case accounts.FieldBalance:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBalance(v)
		return nil
	}
	return fmt.Errorf("unknown Accounts numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AccountsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AccountsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AccountsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Accounts nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AccountsMutation) ResetField(name string) error {
	switch name {
	case accounts.FieldOwner:
		m.ResetOwner()
		return nil
	case accounts.FieldBalance:
		m.ResetBalance()
		return nil
	case accounts.FieldCurrency:
		m.ResetCurrency()
		return nil
	case accounts.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Accounts field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AccountsMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.from_account_id != nil {
		edges = append(edges, accounts.EdgeFromAccountID)
	}
	if m.to_account_id != nil {
		edges = append(edges, accounts.EdgeToAccountID)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AccountsMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case accounts.EdgeFromAccountID:
		ids := make([]ent.Value, 0, len(m.from_account_id))
		for id := range m.from_account_id {
			ids = append(ids, id)
		}
		return ids
	case accounts.EdgeToAccountID:
		ids := make([]ent.Value, 0, len(m.to_account_id))
		for id := range m.to_account_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AccountsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedfrom_account_id != nil {
		edges = append(edges, accounts.EdgeFromAccountID)
	}
	if m.removedto_account_id != nil {
		edges = append(edges, accounts.EdgeToAccountID)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AccountsMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case accounts.EdgeFromAccountID:
		ids := make([]ent.Value, 0, len(m.removedfrom_account_id))
		for id := range m.removedfrom_account_id {
			ids = append(ids, id)
		}
		return ids
	case accounts.EdgeToAccountID:
		ids := make([]ent.Value, 0, len(m.removedto_account_id))
		for id := range m.removedto_account_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AccountsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedfrom_account_id {
		edges = append(edges, accounts.EdgeFromAccountID)
	}
	if m.clearedto_account_id {
		edges = append(edges, accounts.EdgeToAccountID)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AccountsMutation) EdgeCleared(name string) bool {
	switch name {
	case accounts.EdgeFromAccountID:
		return m.clearedfrom_account_id
	case accounts.EdgeToAccountID:
		return m.clearedto_account_id
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AccountsMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Accounts unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AccountsMutation) ResetEdge(name string) error {
	switch name {
	case accounts.EdgeFromAccountID:
		m.ResetFromAccountID()
		return nil
	case accounts.EdgeToAccountID:
		m.ResetToAccountID()
		return nil
	}
	return fmt.Errorf("unknown Accounts edge %s", name)
}

// TransfersMutation represents an operation that mutates the Transfers nodes in the graph.
type TransfersMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	from_account_id    *int
	addfrom_account_id *int
	to_account_id      *int
	addto_account_id   *int
	amount             *int64
	addamount          *int64
	created_at         *time.Time
	clearedFields      map[string]struct{}
	account_of         *int
	clearedaccount_of  bool
	account_to         *int
	clearedaccount_to  bool
	done               bool
	oldValue           func(context.Context) (*Transfers, error)
	predicates         []predicate.Transfers
}

var _ ent.Mutation = (*TransfersMutation)(nil)

// transfersOption allows management of the mutation configuration using functional options.
type transfersOption func(*TransfersMutation)

// newTransfersMutation creates new mutation for the Transfers entity.
func newTransfersMutation(c config, op Op, opts ...transfersOption) *TransfersMutation {
	m := &TransfersMutation{
		config:        c,
		op:            op,
		typ:           TypeTransfers,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTransfersID sets the ID field of the mutation.
func withTransfersID(id int) transfersOption {
	return func(m *TransfersMutation) {
		var (
			err   error
			once  sync.Once
			value *Transfers
		)
		m.oldValue = func(ctx context.Context) (*Transfers, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Transfers.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTransfers sets the old Transfers of the mutation.
func withTransfers(node *Transfers) transfersOption {
	return func(m *TransfersMutation) {
		m.oldValue = func(context.Context) (*Transfers, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TransfersMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TransfersMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TransfersMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetFromAccountID sets the "from_account_id" field.
func (m *TransfersMutation) SetFromAccountID(i int) {
	m.from_account_id = &i
	m.addfrom_account_id = nil
}

// FromAccountID returns the value of the "from_account_id" field in the mutation.
func (m *TransfersMutation) FromAccountID() (r int, exists bool) {
	v := m.from_account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldFromAccountID returns the old "from_account_id" field's value of the Transfers entity.
// If the Transfers object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransfersMutation) OldFromAccountID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldFromAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldFromAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFromAccountID: %w", err)
	}
	return oldValue.FromAccountID, nil
}

// AddFromAccountID adds i to the "from_account_id" field.
func (m *TransfersMutation) AddFromAccountID(i int) {
	if m.addfrom_account_id != nil {
		*m.addfrom_account_id += i
	} else {
		m.addfrom_account_id = &i
	}
}

// AddedFromAccountID returns the value that was added to the "from_account_id" field in this mutation.
func (m *TransfersMutation) AddedFromAccountID() (r int, exists bool) {
	v := m.addfrom_account_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetFromAccountID resets all changes to the "from_account_id" field.
func (m *TransfersMutation) ResetFromAccountID() {
	m.from_account_id = nil
	m.addfrom_account_id = nil
}

// SetToAccountID sets the "to_account_id" field.
func (m *TransfersMutation) SetToAccountID(i int) {
	m.to_account_id = &i
	m.addto_account_id = nil
}

// ToAccountID returns the value of the "to_account_id" field in the mutation.
func (m *TransfersMutation) ToAccountID() (r int, exists bool) {
	v := m.to_account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldToAccountID returns the old "to_account_id" field's value of the Transfers entity.
// If the Transfers object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransfersMutation) OldToAccountID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldToAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldToAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToAccountID: %w", err)
	}
	return oldValue.ToAccountID, nil
}

// AddToAccountID adds i to the "to_account_id" field.
func (m *TransfersMutation) AddToAccountID(i int) {
	if m.addto_account_id != nil {
		*m.addto_account_id += i
	} else {
		m.addto_account_id = &i
	}
}

// AddedToAccountID returns the value that was added to the "to_account_id" field in this mutation.
func (m *TransfersMutation) AddedToAccountID() (r int, exists bool) {
	v := m.addto_account_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetToAccountID resets all changes to the "to_account_id" field.
func (m *TransfersMutation) ResetToAccountID() {
	m.to_account_id = nil
	m.addto_account_id = nil
}

// SetAmount sets the "amount" field.
func (m *TransfersMutation) SetAmount(i int64) {
	m.amount = &i
	m.addamount = nil
}

// Amount returns the value of the "amount" field in the mutation.
func (m *TransfersMutation) Amount() (r int64, exists bool) {
	v := m.amount
	if v == nil {
		return
	}
	return *v, true
}

// OldAmount returns the old "amount" field's value of the Transfers entity.
// If the Transfers object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransfersMutation) OldAmount(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAmount: %w", err)
	}
	return oldValue.Amount, nil
}

// AddAmount adds i to the "amount" field.
func (m *TransfersMutation) AddAmount(i int64) {
	if m.addamount != nil {
		*m.addamount += i
	} else {
		m.addamount = &i
	}
}

// AddedAmount returns the value that was added to the "amount" field in this mutation.
func (m *TransfersMutation) AddedAmount() (r int64, exists bool) {
	v := m.addamount
	if v == nil {
		return
	}
	return *v, true
}

// ResetAmount resets all changes to the "amount" field.
func (m *TransfersMutation) ResetAmount() {
	m.amount = nil
	m.addamount = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *TransfersMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TransfersMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Transfers entity.
// If the Transfers object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransfersMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TransfersMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetAccountOfID sets the "account_of" edge to the Accounts entity by id.
func (m *TransfersMutation) SetAccountOfID(id int) {
	m.account_of = &id
}

// ClearAccountOf clears the "account_of" edge to the Accounts entity.
func (m *TransfersMutation) ClearAccountOf() {
	m.clearedaccount_of = true
}

// AccountOfCleared reports if the "account_of" edge to the Accounts entity was cleared.
func (m *TransfersMutation) AccountOfCleared() bool {
	return m.clearedaccount_of
}

// AccountOfID returns the "account_of" edge ID in the mutation.
func (m *TransfersMutation) AccountOfID() (id int, exists bool) {
	if m.account_of != nil {
		return *m.account_of, true
	}
	return
}

// AccountOfIDs returns the "account_of" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AccountOfID instead. It exists only for internal usage by the builders.
func (m *TransfersMutation) AccountOfIDs() (ids []int) {
	if id := m.account_of; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAccountOf resets all changes to the "account_of" edge.
func (m *TransfersMutation) ResetAccountOf() {
	m.account_of = nil
	m.clearedaccount_of = false
}

// SetAccountToID sets the "account_to" edge to the Accounts entity by id.
func (m *TransfersMutation) SetAccountToID(id int) {
	m.account_to = &id
}

// ClearAccountTo clears the "account_to" edge to the Accounts entity.
func (m *TransfersMutation) ClearAccountTo() {
	m.clearedaccount_to = true
}

// AccountToCleared reports if the "account_to" edge to the Accounts entity was cleared.
func (m *TransfersMutation) AccountToCleared() bool {
	return m.clearedaccount_to
}

// AccountToID returns the "account_to" edge ID in the mutation.
func (m *TransfersMutation) AccountToID() (id int, exists bool) {
	if m.account_to != nil {
		return *m.account_to, true
	}
	return
}

// AccountToIDs returns the "account_to" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AccountToID instead. It exists only for internal usage by the builders.
func (m *TransfersMutation) AccountToIDs() (ids []int) {
	if id := m.account_to; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAccountTo resets all changes to the "account_to" edge.
func (m *TransfersMutation) ResetAccountTo() {
	m.account_to = nil
	m.clearedaccount_to = false
}

// Where appends a list predicates to the TransfersMutation builder.
func (m *TransfersMutation) Where(ps ...predicate.Transfers) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TransfersMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Transfers).
func (m *TransfersMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TransfersMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.from_account_id != nil {
		fields = append(fields, transfers.FieldFromAccountID)
	}
	if m.to_account_id != nil {
		fields = append(fields, transfers.FieldToAccountID)
	}
	if m.amount != nil {
		fields = append(fields, transfers.FieldAmount)
	}
	if m.created_at != nil {
		fields = append(fields, transfers.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TransfersMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case transfers.FieldFromAccountID:
		return m.FromAccountID()
	case transfers.FieldToAccountID:
		return m.ToAccountID()
	case transfers.FieldAmount:
		return m.Amount()
	case transfers.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TransfersMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case transfers.FieldFromAccountID:
		return m.OldFromAccountID(ctx)
	case transfers.FieldToAccountID:
		return m.OldToAccountID(ctx)
	case transfers.FieldAmount:
		return m.OldAmount(ctx)
	case transfers.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Transfers field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TransfersMutation) SetField(name string, value ent.Value) error {
	switch name {
	case transfers.FieldFromAccountID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFromAccountID(v)
		return nil
	case transfers.FieldToAccountID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToAccountID(v)
		return nil
	case transfers.FieldAmount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAmount(v)
		return nil
	case transfers.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Transfers field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TransfersMutation) AddedFields() []string {
	var fields []string
	if m.addfrom_account_id != nil {
		fields = append(fields, transfers.FieldFromAccountID)
	}
	if m.addto_account_id != nil {
		fields = append(fields, transfers.FieldToAccountID)
	}
	if m.addamount != nil {
		fields = append(fields, transfers.FieldAmount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TransfersMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case transfers.FieldFromAccountID:
		return m.AddedFromAccountID()
	case transfers.FieldToAccountID:
		return m.AddedToAccountID()
	case transfers.FieldAmount:
		return m.AddedAmount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TransfersMutation) AddField(name string, value ent.Value) error {
	switch name {
	case transfers.FieldFromAccountID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFromAccountID(v)
		return nil
	case transfers.FieldToAccountID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddToAccountID(v)
		return nil
	case transfers.FieldAmount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAmount(v)
		return nil
	}
	return fmt.Errorf("unknown Transfers numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TransfersMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TransfersMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TransfersMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Transfers nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TransfersMutation) ResetField(name string) error {
	switch name {
	case transfers.FieldFromAccountID:
		m.ResetFromAccountID()
		return nil
	case transfers.FieldToAccountID:
		m.ResetToAccountID()
		return nil
	case transfers.FieldAmount:
		m.ResetAmount()
		return nil
	case transfers.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Transfers field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TransfersMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.account_of != nil {
		edges = append(edges, transfers.EdgeAccountOf)
	}
	if m.account_to != nil {
		edges = append(edges, transfers.EdgeAccountTo)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TransfersMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case transfers.EdgeAccountOf:
		if id := m.account_of; id != nil {
			return []ent.Value{*id}
		}
	case transfers.EdgeAccountTo:
		if id := m.account_to; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TransfersMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TransfersMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TransfersMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedaccount_of {
		edges = append(edges, transfers.EdgeAccountOf)
	}
	if m.clearedaccount_to {
		edges = append(edges, transfers.EdgeAccountTo)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TransfersMutation) EdgeCleared(name string) bool {
	switch name {
	case transfers.EdgeAccountOf:
		return m.clearedaccount_of
	case transfers.EdgeAccountTo:
		return m.clearedaccount_to
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TransfersMutation) ClearEdge(name string) error {
	switch name {
	case transfers.EdgeAccountOf:
		m.ClearAccountOf()
		return nil
	case transfers.EdgeAccountTo:
		m.ClearAccountTo()
		return nil
	}
	return fmt.Errorf("unknown Transfers unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TransfersMutation) ResetEdge(name string) error {
	switch name {
	case transfers.EdgeAccountOf:
		m.ResetAccountOf()
		return nil
	case transfers.EdgeAccountTo:
		m.ResetAccountTo()
		return nil
	}
	return fmt.Errorf("unknown Transfers edge %s", name)
}
