// Code generated by entc, DO NOT EDIT.

package ent

import (
	"gomicro/ent/accounts"
	"gomicro/ent/schema"
	"gomicro/ent/transfers"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountsFields := schema.Accounts{}.Fields()
	_ = accountsFields
	// accountsDescOwner is the schema descriptor for owner field.
	accountsDescOwner := accountsFields[0].Descriptor()
	// accounts.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	accounts.OwnerValidator = accountsDescOwner.Validators[0].(func(string) error)
	// accountsDescBalance is the schema descriptor for balance field.
	accountsDescBalance := accountsFields[1].Descriptor()
	// accounts.DefaultBalance holds the default value on creation for the balance field.
	accounts.DefaultBalance = accountsDescBalance.Default.(int64)
	// accounts.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	accounts.BalanceValidator = accountsDescBalance.Validators[0].(func(int64) error)
	// accountsDescCurrency is the schema descriptor for currency field.
	accountsDescCurrency := accountsFields[2].Descriptor()
	// accounts.DefaultCurrency holds the default value on creation for the currency field.
	accounts.DefaultCurrency = accountsDescCurrency.Default.(string)
	// accounts.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	accounts.CurrencyValidator = accountsDescCurrency.Validators[0].(func(string) error)
	// accountsDescCreatedAt is the schema descriptor for created_at field.
	accountsDescCreatedAt := accountsFields[3].Descriptor()
	// accounts.DefaultCreatedAt holds the default value on creation for the created_at field.
	accounts.DefaultCreatedAt = accountsDescCreatedAt.Default.(func() time.Time)
	transfersFields := schema.Transfers{}.Fields()
	_ = transfersFields
	// transfersDescFromAccountID is the schema descriptor for from_account_id field.
	transfersDescFromAccountID := transfersFields[0].Descriptor()
	// transfers.FromAccountIDValidator is a validator for the "from_account_id" field. It is called by the builders before save.
	transfers.FromAccountIDValidator = transfersDescFromAccountID.Validators[0].(func(int) error)
	// transfersDescToAccountID is the schema descriptor for to_account_id field.
	transfersDescToAccountID := transfersFields[1].Descriptor()
	// transfers.ToAccountIDValidator is a validator for the "to_account_id" field. It is called by the builders before save.
	transfers.ToAccountIDValidator = transfersDescToAccountID.Validators[0].(func(int) error)
	// transfersDescAmount is the schema descriptor for amount field.
	transfersDescAmount := transfersFields[2].Descriptor()
	// transfers.DefaultAmount holds the default value on creation for the amount field.
	transfers.DefaultAmount = transfersDescAmount.Default.(int64)
	// transfers.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	transfers.AmountValidator = transfersDescAmount.Validators[0].(func(int64) error)
	// transfersDescCreatedAt is the schema descriptor for created_at field.
	transfersDescCreatedAt := transfersFields[3].Descriptor()
	// transfers.DefaultCreatedAt holds the default value on creation for the created_at field.
	transfers.DefaultCreatedAt = transfersDescCreatedAt.Default.(func() time.Time)
}
