// Code generated by entc, DO NOT EDIT.

package ent

import (
	"gomicro/ent/accounts"
	"gomicro/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountsFields := schema.Accounts{}.Fields()
	_ = accountsFields
	// accountsDescOwner is the schema descriptor for owner field.
	accountsDescOwner := accountsFields[0].Descriptor()
	// accounts.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	accounts.OwnerValidator = accountsDescOwner.Validators[0].(func(string) error)
	// accountsDescBalance is the schema descriptor for balance field.
	accountsDescBalance := accountsFields[1].Descriptor()
	// accounts.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	accounts.BalanceValidator = accountsDescBalance.Validators[0].(func(int64) error)
	// accountsDescCurrency is the schema descriptor for currency field.
	accountsDescCurrency := accountsFields[2].Descriptor()
	// accounts.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	accounts.CurrencyValidator = accountsDescCurrency.Validators[0].(func(string) error)
	// accountsDescCreatedAt is the schema descriptor for created_at field.
	accountsDescCreatedAt := accountsFields[3].Descriptor()
	// accounts.DefaultCreatedAt holds the default value on creation for the created_at field.
	accounts.DefaultCreatedAt = accountsDescCreatedAt.Default.(func() time.Time)
}
