// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gomicro/ent/accounts"
	"gomicro/ent/transfers"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransfersCreate is the builder for creating a Transfers entity.
type TransfersCreate struct {
	config
	mutation *TransfersMutation
	hooks    []Hook
}

// SetFromAccountID sets the "from_account_id" field.
func (tc *TransfersCreate) SetFromAccountID(i int) *TransfersCreate {
	tc.mutation.SetFromAccountID(i)
	return tc
}

// SetToAccountID sets the "to_account_id" field.
func (tc *TransfersCreate) SetToAccountID(i int) *TransfersCreate {
	tc.mutation.SetToAccountID(i)
	return tc
}

// SetAmount sets the "amount" field.
func (tc *TransfersCreate) SetAmount(i int64) *TransfersCreate {
	tc.mutation.SetAmount(i)
	return tc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tc *TransfersCreate) SetNillableAmount(i *int64) *TransfersCreate {
	if i != nil {
		tc.SetAmount(*i)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TransfersCreate) SetCreatedAt(t time.Time) *TransfersCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TransfersCreate) SetNillableCreatedAt(t *time.Time) *TransfersCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetAccountOfID sets the "account_of" edge to the Accounts entity by ID.
func (tc *TransfersCreate) SetAccountOfID(id int) *TransfersCreate {
	tc.mutation.SetAccountOfID(id)
	return tc
}

// SetNillableAccountOfID sets the "account_of" edge to the Accounts entity by ID if the given value is not nil.
func (tc *TransfersCreate) SetNillableAccountOfID(id *int) *TransfersCreate {
	if id != nil {
		tc = tc.SetAccountOfID(*id)
	}
	return tc
}

// SetAccountOf sets the "account_of" edge to the Accounts entity.
func (tc *TransfersCreate) SetAccountOf(a *Accounts) *TransfersCreate {
	return tc.SetAccountOfID(a.ID)
}

// SetAccountToID sets the "account_to" edge to the Accounts entity by ID.
func (tc *TransfersCreate) SetAccountToID(id int) *TransfersCreate {
	tc.mutation.SetAccountToID(id)
	return tc
}

// SetNillableAccountToID sets the "account_to" edge to the Accounts entity by ID if the given value is not nil.
func (tc *TransfersCreate) SetNillableAccountToID(id *int) *TransfersCreate {
	if id != nil {
		tc = tc.SetAccountToID(*id)
	}
	return tc
}

// SetAccountTo sets the "account_to" edge to the Accounts entity.
func (tc *TransfersCreate) SetAccountTo(a *Accounts) *TransfersCreate {
	return tc.SetAccountToID(a.ID)
}

// Mutation returns the TransfersMutation object of the builder.
func (tc *TransfersCreate) Mutation() *TransfersMutation {
	return tc.mutation
}

// Save creates the Transfers in the database.
func (tc *TransfersCreate) Save(ctx context.Context) (*Transfers, error) {
	var (
		err  error
		node *Transfers
	)
	tc.defaults()
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransfersMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TransfersCreate) SaveX(ctx context.Context) *Transfers {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TransfersCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TransfersCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TransfersCreate) defaults() {
	if _, ok := tc.mutation.Amount(); !ok {
		v := transfers.DefaultAmount
		tc.mutation.SetAmount(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := transfers.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TransfersCreate) check() error {
	if _, ok := tc.mutation.FromAccountID(); !ok {
		return &ValidationError{Name: "from_account_id", err: errors.New(`ent: missing required field "from_account_id"`)}
	}
	if v, ok := tc.mutation.FromAccountID(); ok {
		if err := transfers.FromAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "from_account_id", err: fmt.Errorf(`ent: validator failed for field "from_account_id": %w`, err)}
		}
	}
	if _, ok := tc.mutation.ToAccountID(); !ok {
		return &ValidationError{Name: "to_account_id", err: errors.New(`ent: missing required field "to_account_id"`)}
	}
	if v, ok := tc.mutation.ToAccountID(); ok {
		if err := transfers.ToAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "to_account_id", err: fmt.Errorf(`ent: validator failed for field "to_account_id": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "amount"`)}
	}
	if v, ok := tc.mutation.Amount(); ok {
		if err := transfers.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "amount": %w`, err)}
		}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	return nil
}

func (tc *TransfersCreate) sqlSave(ctx context.Context) (*Transfers, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *TransfersCreate) createSpec() (*Transfers, *sqlgraph.CreateSpec) {
	var (
		_node = &Transfers{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: transfers.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transfers.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.FromAccountID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: transfers.FieldFromAccountID,
		})
		_node.FromAccountID = value
	}
	if value, ok := tc.mutation.ToAccountID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: transfers.FieldToAccountID,
		})
		_node.ToAccountID = value
	}
	if value, ok := tc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: transfers.FieldAmount,
		})
		_node.Amount = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: transfers.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := tc.mutation.AccountOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transfers.AccountOfTable,
			Columns: []string{transfers.AccountOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: accounts.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.accounts_from_account_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.AccountToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transfers.AccountToTable,
			Columns: []string{transfers.AccountToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: accounts.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.accounts_to_account_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransfersCreateBulk is the builder for creating many Transfers entities in bulk.
type TransfersCreateBulk struct {
	config
	builders []*TransfersCreate
}

// Save creates the Transfers entities in the database.
func (tcb *TransfersCreateBulk) Save(ctx context.Context) ([]*Transfers, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Transfers, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransfersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TransfersCreateBulk) SaveX(ctx context.Context) []*Transfers {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TransfersCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TransfersCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
