name: Automatic draft PR

on:
  push:
    branches:
      - feature/**
      - fix/**
      - feat/**
      - chore/**

jobs:
  auto-pull-request:
    name: Create or update draft pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
      packages: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Create or update pull request
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: ":crown: *An automated PR*"
          pr_reviewer: "kingdonb"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
