name: ci

on:
  push:
    branches: [main, ci]
  pull_request_target:
    branches: [main, ci]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"

      - name: Dagger lint
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run ci/main.go -lint

      - name: Dagger test
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run ci/main.go -test
  publish:
    runs-on: ubuntu-latest
    needs: lint_and_test
    permissions:
      contents: write
      packages: write
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"

      - name: Dagger build
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run ci/main.go -build

