name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"
      - name: Dagger
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run ci/main.go -lint
  test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres:12-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Docker Container
        run: docker ps

      - name: Start Postgres in docker
        run: make startpg

      - name: Create test database
        run: make createdb

      - name: Create test tables
        run: make createtable

      - name: Run all Test
        run: make test

      - name: Delete database
        run: make dropdb

      - name: Delete postgres
        run: make stoppg
