name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - ci
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  name: Dagger CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Dagger CLI
      run: |
        curl -sSL https://get.dagger.io/cli.sh | bash
        sudo mv dagger /usr/local/bin/

    - name: Run Dagger lint command
      run: dagger run go run ci/main.go -lint