name: "PR Labeler"
on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: "supareel/template_microservice"
    - name: Pull Request Labeler
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # configuration-path: ".github/labeler.yml" # Path to your labeler configuration file

