// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Accounts is the predicate function for accounts builders.
type Accounts func(*sql.Selector)

// Transfers is the predicate function for transfers builders.
type Transfers func(*sql.Selector)
